# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bac6b0d436bfe5ec3516a8b30d683ce79418ee4d6b991924f0742402b92dc8676d05918c95560e78c68586baceac5ac0145b2475fa96e146799e92f331b47cc

test:
  secret_key_base: 544433bce4431d21826aab798ca0ea492a324dae60211f6b4e250998488875903ea96ed6e1bb662aa233e4bc7c334ffcd5d1a8ebdca4b8b71fa8f1a394ce9887

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
